### ISSUE TITLE
What's the mmcv version?

### ISSUE THREAD

**Issue by Icecream-blue-sky** [CityU-AIM-Group/HTD#1]

**Comment by Icecream-blue-sky** [comment]
I find that your code and mmdet version don't match. For example, in bbox_nms.py: from mmdet.ops.nms import batched_nms, nms_wrapper. There isn't ops/nms folder under mmdet folder. Do you succesfully run your code by yourself ? If yes, please provide your conda and pip list. I can't run the code succesfully after install correct mmdet and mmcv.

**Comment by wymanCV** [comment]
Hi, sorry for the late reply. My detailed environment is as follows, 

mmcv-full: 1.2.1 
mmdet: 2.7
cudatoolkit: 10.0
torch: 1.6.0

As you know, the old version of mmdet has lots of compatibility issues. I didn't use the compiled mmcv package and git and compile it using the local GPU following the installation instruction. The mmdet.ops.nms should be directly installed in your conda environment.  I have uploaded my local 'ops' folder and I hope it will be helpful.

**Comment by Icecream-blue-sky** [comment]
> Hi, sorry for the late reply. My detailed environment is as follows,
> 
> mmcv-full: 1.2.1 mmdet: 2.7 cudatoolkit: 10.0 torch: 1.6.0
> 
> As you know, the old version of mmdet has lots of compatibility issues. I didn't use the compiled mmcv package and git and compile it using the local GPU following the installation instruction. The mmdet.ops.nms should be directly installed in your conda environment. I have uploaded my local 'ops' folder and I hope it will be helpful.

Thanks, I'll try.

**Comment by wymanCV** [comment]
It seems that you are also researching GCN and object detection. Welcome to add my WeChat "huhu19980526"  for a quick reply.
